import type { Artifact } from './types';

/* ============================================================
   MUSEUM WARS — ARTIFACT DATABASE  (PASS 1 of 2)
   200 real, documented artworks — ids 0011..0210.
   Follows the expansion plan's rarity pyramid and style spread.
   Pass 2 (ids 0211+) appends the remaining ~200.
   `value` is a baseline auction price; rarity derives from `score`.
   `image` -> /artifacts/<id>.jpg; a letter placeholder shows until
   the file exists.
   ============================================================ */

export const ARTIFACTS_PASS1: Artifact[] = [
  /* ===================== RENAISSANCE ===================== */
  { id: '0011', name: 'The Last Supper', type: 'Painting', style: 'renaissance',
    author: 'Leonardo da Vinci', year: 'c. 1498',
    description: 'A mural of Christ and the apostles at the moment of betrayal foretold.',
    score: 232, value: 2280000, image: 'artifacts/0011.jpg' },
  { id: '0012', name: 'The Birth of Venus', type: 'Painting', style: 'renaissance',
    author: 'Sandro Botticelli', year: 'c. 1485',
    description: 'The goddess arrives ashore on a shell, borne by the breath of the winds.',
    score: 188, value: 1820000, image: 'artifacts/0012.jpg' },
  { id: '0013', name: 'The School of Athens', type: 'Painting', style: 'renaissance',
    author: 'Raphael', year: 'c. 1511',
    description: 'The great philosophers of antiquity gather beneath a vast vaulted hall.',
    score: 176, value: 1700000, image: 'artifacts/0013.jpg' },
  { id: '0014', name: 'Primavera', type: 'Painting', style: 'renaissance',
    author: 'Sandro Botticelli', year: 'c. 1480',
    description: 'Figures of spring move through an orange grove in measured grace.',
    score: 162, value: 1560000, image: 'artifacts/0014.jpg' },
  { id: '0015', name: 'The Creation of Adam', type: 'Painting', style: 'renaissance',
    author: 'Michelangelo', year: 'c. 1512',
    description: 'God reaches toward Adam, their fingers nearly touching across the void.',
    score: 198, value: 1940000, image: 'artifacts/0015.jpg' },
  { id: '0016', name: 'The Arnolfini Portrait', type: 'Painting', style: 'renaissance',
    author: 'Jan van Eyck', year: '1434',
    description: 'A couple stand in a richly furnished room, a convex mirror behind them.',
    score: 134, value: 1280000, image: 'artifacts/0016.jpg' },
  { id: '0017', name: 'Pietà', type: 'Sculpture', style: 'renaissance',
    author: 'Michelangelo', year: 'c. 1499',
    description: 'The Virgin cradles the body of Christ, carved from a single marble block.',
    score: 184, value: 1780000, image: 'artifacts/0017.jpg' },
  { id: '0018', name: 'Lady with an Ermine', type: 'Painting', style: 'renaissance',
    author: 'Leonardo da Vinci', year: 'c. 1490',
    description: 'A young woman turns gently, an ermine held against her dark gown.',
    score: 128, value: 1220000, image: 'artifacts/0018.jpg' },
  { id: '0019', name: 'The Tempest', type: 'Painting', style: 'renaissance',
    author: 'Giorgione', year: 'c. 1508',
    description: 'A soldier and a nursing woman pause in a landscape under gathering storm.',
    score: 74, value: 720000, image: 'artifacts/0019.jpg' },
  { id: '0020', name: 'Portrait of a Young Man', type: 'Painting', style: 'renaissance',
    author: 'Agnolo Bronzino', year: 'c. 1540',
    description: 'A composed youth in black, one hand resting on a closed book.',
    score: 41, value: 410000, image: 'artifacts/0020.jpg' },
  { id: '0021', name: 'Madonna of the Goldfinch', type: 'Painting', style: 'renaissance',
    author: 'Raphael', year: 'c. 1506',
    description: 'The Virgin watches over two children and a small bird held between them.',
    score: 68, value: 660000, image: 'artifacts/0021.jpg' },
  { id: '0022', name: 'Bacchus', type: 'Sculpture', style: 'renaissance',
    author: 'Michelangelo', year: 'c. 1497',
    description: 'A marble god of wine sways, a cup raised, a young satyr at his side.',
    score: 79, value: 770000, image: 'artifacts/0022.jpg' },
  { id: '0023', name: 'Studies of the Foetus in the Womb', type: 'Manuscript', style: 'renaissance',
    author: 'Leonardo da Vinci', year: 'c. 1511',
    description: 'Anatomical drawings in red chalk, dense with mirror-written notes.',
    score: 57, value: 560000, image: 'artifacts/0023.jpg' },
  { id: '0024', name: 'Portrait of a Lady', type: 'Painting', style: 'renaissance',
    author: 'Workshop of Domenico Ghirlandaio', year: 'c. 1490',
    description: 'A Florentine woman in profile, jewels bright against a dark ground.',
    score: 16, value: 160000, image: 'artifacts/0024.jpg' },
  { id: '0025', name: 'Study of Drapery', type: 'Manuscript', style: 'renaissance',
    author: 'Workshop of Leonardo da Vinci', year: 'c. 1480',
    description: 'A cloth study in grey wash, folds modelled with patient light.',
    score: 7, value: 60000, image: 'artifacts/0025.jpg' },
  { id: '0026', name: 'Devotional Panel of the Virgin', type: 'Painting', style: 'renaissance',
    author: 'Unknown', year: 'c. 1470',
    description: 'A small gilded panel of the Virgin, made for private prayer.',
    score: 12, value: 120000, image: 'artifacts/0026.jpg' },
  { id: '0027', name: 'Marble Portrait Bust of a Patron', type: 'Sculpture', style: 'renaissance',
    author: 'Unknown', year: 'c. 1475',
    description: 'A merchant\u2019s likeness in marble, lined and unidealised.',
    score: 23, value: 230000, image: 'artifacts/0027.jpg' },
  { id: '0028', name: 'Cassone Panel with a Procession', type: 'Painting', style: 'renaissance',
    author: 'Unknown', year: 'c. 1465',
    description: 'A painted marriage-chest panel showing a festive civic procession.',
    score: 9, value: 80000, image: 'artifacts/0028.jpg' },
  { id: '0029', name: 'Sketch of a Rearing Horse', type: 'Manuscript', style: 'renaissance',
    author: 'Workshop of Leonardo da Vinci', year: 'c. 1490',
    description: 'A swift pen study of a horse, the same pose tried several times.',
    score: 14, value: 140000, image: 'artifacts/0029.jpg' },
  { id: '0030', name: 'The Annunciation', type: 'Painting', style: 'renaissance',
    author: 'Fra Angelico', year: 'c. 1440',
    description: 'The angel kneels before the Virgin in a bright tiled loggia.',
    score: 88, value: 860000, image: 'artifacts/0030.jpg' },
  { id: '0031', name: 'Battle of San Romano', type: 'Painting', style: 'renaissance',
    author: 'Paolo Uccello', year: 'c. 1438',
    description: 'Lances and fallen knights laid out in bold, almost geometric order.',
    score: 71, value: 690000, image: 'artifacts/0031.jpg' },
  { id: '0032', name: 'Bronze Relief of a Sacrifice', type: 'Sculpture', style: 'renaissance',
    author: 'Workshop of Lorenzo Ghiberti', year: 'c. 1425',
    description: 'A gilded bronze panel crowded with figures in shallow relief.',
    score: 34, value: 340000, image: 'artifacts/0032.jpg' },
  { id: '0033', name: 'Choir Stall Carving', type: 'Sculpture', style: 'renaissance',
    author: 'Unknown', year: 'c. 1480',
    description: 'An inlaid wood panel showing a city seen through an open arch.',
    score: 6, value: 50000, image: 'artifacts/0033.jpg' },
  { id: '0034', name: 'Illuminated Choir Book Leaf', type: 'Manuscript', style: 'renaissance',
    author: 'Unknown', year: 'c. 1460',
    description: 'A large vellum leaf with a historiated initial and music staves.',
    score: 18, value: 180000, image: 'artifacts/0034.jpg' },
  { id: '0035', name: 'Portrait Medal of a Duke', type: 'Object', style: 'renaissance',
    author: 'Workshop of Pisanello', year: 'c. 1450',
    description: 'A cast bronze medal, a ruler\u2019s profile on one face, an emblem on the other.',
    score: 11, value: 110000, image: 'artifacts/0035.jpg' },
  { id: '0036', name: 'Maiolica Dish with a Coat of Arms', type: 'Object', style: 'renaissance',
    author: 'Unknown', year: 'c. 1520',
    description: 'A tin-glazed dish painted with a family\u2019s arms and bright grotesques.',
    score: 8, value: 70000, image: 'artifacts/0036.jpg' },

  /* ===================== BAROQUE ===================== */
  { id: '0037', name: 'The Night Watch', type: 'Painting', style: 'baroque',
    author: 'Rembrandt van Rijn', year: '1642',
    description: 'A militia company steps forward out of shadow into sudden light.',
    score: 196, value: 1920000, image: 'artifacts/0037.jpg' },
  { id: '0038', name: 'Girl with a Pearl Earring', type: 'Painting', style: 'baroque',
    author: 'Johannes Vermeer', year: 'c. 1665',
    description: 'A girl turns toward the viewer, a single pearl catching the light.',
    score: 182, value: 1760000, image: 'artifacts/0038.jpg' },
  { id: '0039', name: 'Las Meninas', type: 'Painting', style: 'baroque',
    author: 'Diego Velázquez', year: '1656',
    description: 'A young princess and her attendants, the painter himself at his easel.',
    score: 190, value: 1860000, image: 'artifacts/0039.jpg' },
  { id: '0040', name: 'Judith Slaying Holofernes', type: 'Painting', style: 'baroque',
    author: 'Artemisia Gentileschi', year: 'c. 1620',
    description: 'A scene of violent resolve, lit with sharp Caravaggesque contrast.',
    score: 121, value: 1160000, image: 'artifacts/0040.jpg' },
  { id: '0041', name: 'The Calling of Saint Matthew', type: 'Painting', style: 'baroque',
    author: 'Caravaggio', year: 'c. 1600',
    description: 'A shaft of light cuts across a tavern as a tax collector is called.',
    score: 138, value: 1320000, image: 'artifacts/0041.jpg' },
  { id: '0042', name: 'Apollo and Daphne', type: 'Sculpture', style: 'baroque',
    author: 'Gian Lorenzo Bernini', year: 'c. 1625',
    description: 'A marble group caught at the instant a fleeing nymph turns to laurel.',
    score: 154, value: 1480000, image: 'artifacts/0042.jpg' },
  { id: '0043', name: 'The Milkmaid', type: 'Painting', style: 'baroque',
    author: 'Johannes Vermeer', year: 'c. 1658',
    description: 'A servant pours milk in a quiet room flooded with even daylight.',
    score: 116, value: 1110000, image: 'artifacts/0043.jpg' },
  { id: '0044', name: 'Self-Portrait with Two Circles', type: 'Painting', style: 'baroque',
    author: 'Rembrandt van Rijn', year: 'c. 1665',
    description: 'The aged painter stands with brushes and palette before two mysterious arcs.',
    score: 92, value: 900000, image: 'artifacts/0044.jpg' },
  { id: '0045', name: 'Still Life with a Lobster', type: 'Painting', style: 'baroque',
    author: 'Unknown', year: 'c. 1650',
    description: 'A laden table of fruit, glass and shellfish glowing against the dark.',
    score: 27, value: 270000, image: 'artifacts/0045.jpg' },
  { id: '0046', name: 'Vanitas with a Skull', type: 'Painting', style: 'baroque',
    author: 'Unknown', year: 'c. 1640',
    description: 'A skull, a guttering candle and a watch — a meditation on passing time.',
    score: 31, value: 310000, image: 'artifacts/0046.jpg' },
  { id: '0047', name: 'Portrait of a Dutch Merchant', type: 'Painting', style: 'baroque',
    author: 'Workshop of Frans Hals', year: 'c. 1635',
    description: 'A burgher caught mid-gesture, the brushwork loose and quick.',
    score: 22, value: 220000, image: 'artifacts/0047.jpg' },
  { id: '0048', name: 'A Winter Landscape with Skaters', type: 'Painting', style: 'baroque',
    author: 'Unknown', year: 'c. 1620',
    description: 'Townsfolk skate on a frozen river beneath a pale, wide sky.',
    score: 17, value: 170000, image: 'artifacts/0048.jpg' },
  { id: '0049', name: 'Carved Ivory Crucifix', type: 'Object', style: 'baroque',
    author: 'Unknown', year: 'c. 1660',
    description: 'A finely cut ivory figure mounted on an ebony cross.',
    score: 19, value: 190000, image: 'artifacts/0049.jpg' },
  { id: '0050', name: 'Silver Gilt Altar Cruet', type: 'Object', style: 'baroque',
    author: 'Unknown', year: 'c. 1680',
    description: 'A small liturgical vessel chased with scrolling acanthus leaf.',
    score: 9, value: 80000, image: 'artifacts/0050.jpg' },
  { id: '0051', name: 'Study of a Reclining Figure', type: 'Manuscript', style: 'baroque',
    author: 'Workshop of Peter Paul Rubens', year: 'c. 1620',
    description: 'A chalk study of a heavy male figure, muscles built in confident strokes.',
    score: 13, value: 130000, image: 'artifacts/0051.jpg' },
  { id: '0052', name: 'Marble Portrait Bust of a Cardinal', type: 'Sculpture', style: 'baroque',
    author: 'Unknown', year: 'c. 1670',
    description: 'A churchman in marble, robes carved into deep, restless folds.',
    score: 38, value: 380000, image: 'artifacts/0052.jpg' },
  { id: '0053', name: 'Engraved Pilgrimage Map', type: 'Manuscript', style: 'baroque',
    author: 'Unknown', year: 'c. 1650',
    description: 'A folded engraving marking shrines along a pilgrim road.',
    score: 5, value: 45000, image: 'artifacts/0053.jpg' },
  { id: '0054', name: 'A Concert of Birds', type: 'Painting', style: 'baroque',
    author: 'Unknown', year: 'c. 1665',
    description: 'Dozens of birds gather on a branch in a crowded decorative scene.',
    score: 15, value: 150000, image: 'artifacts/0054.jpg' },

  /* ===================== CLASSICAL ===================== */
  { id: '0055', name: 'Laocoön and His Sons', type: 'Sculpture', style: 'classical',
    author: 'Unknown', year: 'c. 40 BCE',
    description: 'A priest and his sons writhe in the coils of sea serpents.',
    score: 206, value: 2020000, image: 'artifacts/0055.jpg' },
  { id: '0056', name: 'The Discobolus', type: 'Sculpture', style: 'classical',
    author: 'Myron (Roman copy)', year: 'c. 450 BCE',
    description: 'An athlete coiled at the height of his throw, frozen in marble.',
    score: 142, value: 1360000, image: 'artifacts/0056.jpg' },
  { id: '0057', name: 'Winged Victory of Samothrace', type: 'Sculpture', style: 'classical',
    author: 'Unknown', year: 'c. 190 BCE',
    description: 'A winged goddess alights on a ship\u2019s prow, drapery streaming in wind.',
    score: 188, value: 1840000, image: 'artifacts/0057.jpg' },
  { id: '0058', name: 'The Augustus of Prima Porta', type: 'Sculpture', style: 'classical',
    author: 'Unknown', year: 'c. 20 CE',
    description: 'An emperor in armour raises a hand, idealised and eternally young.',
    score: 96, value: 940000, image: 'artifacts/0058.jpg' },
  { id: '0059', name: 'The Dying Gaul', type: 'Sculpture', style: 'classical',
    author: 'Unknown', year: 'c. 230 BCE',
    description: 'A wounded warrior sinks slowly to the ground, sword fallen aside.',
    score: 108, value: 1040000, image: 'artifacts/0059.jpg' },
  { id: '0060', name: 'Bust of Pericles', type: 'Sculpture', style: 'classical',
    author: 'Unknown', year: 'c. 430 BCE',
    description: 'A helmeted statesman in marble, calm and severely composed.',
    score: 47, value: 470000, image: 'artifacts/0060.jpg' },
  { id: '0061', name: 'The Portland Vase', type: 'Object', style: 'classical',
    author: 'Unknown', year: 'c. 25 CE',
    description: 'A cameo-glass vessel in deep blue and white, figures cut in relief.',
    score: 84, value: 820000, image: 'artifacts/0061.jpg' },
  { id: '0062', name: 'Marble Sarcophagus with a Battle', type: 'Sculpture', style: 'classical',
    author: 'Unknown', year: 'c. 250 CE',
    description: 'A coffin carved with a tangle of warriors and rearing horses.',
    score: 53, value: 520000, image: 'artifacts/0062.jpg' },
  { id: '0063', name: 'Red-Figure Amphora with Athletes', type: 'Object', style: 'classical',
    author: 'Unknown', year: 'c. 510 BCE',
    description: 'A tall jar painted with runners in fluid red-figure technique.',
    score: 36, value: 360000, image: 'artifacts/0063.jpg' },
  { id: '0064', name: 'Black-Figure Drinking Cup', type: 'Object', style: 'classical',
    author: 'Unknown', year: 'c. 540 BCE',
    description: 'A shallow wine cup with a ship sailing around its inner surface.',
    score: 21, value: 210000, image: 'artifacts/0064.jpg' },
  { id: '0065', name: 'Roman Floor Mosaic with a Sea-God', type: 'Object', style: 'classical',
    author: 'Unknown', year: 'c. 150 CE',
    description: 'Tesserae form a bearded sea-god ringed by leaping dolphins.',
    score: 29, value: 290000, image: 'artifacts/0065.jpg' },
  { id: '0066', name: 'Bronze Helmet of Corinthian Type', type: 'Object', style: 'classical',
    author: 'Unknown', year: 'c. 500 BCE',
    description: 'A beaten bronze helmet, eye-slits narrow, surface green with age.',
    score: 24, value: 240000, image: 'artifacts/0066.jpg' },
  { id: '0067', name: 'Marble Head of a Goddess', type: 'Sculpture', style: 'classical',
    author: 'Unknown', year: 'c. 350 BCE',
    description: 'A serene marble head, the body long since lost.',
    score: 33, value: 330000, image: 'artifacts/0067.jpg' },
  { id: '0068', name: 'Terracotta Votive Figurine', type: 'Object', style: 'classical',
    author: 'Unknown', year: 'c. 400 BCE',
    description: 'A small moulded figure left as an offering at a sanctuary.',
    score: 6, value: 50000, image: 'artifacts/0068.jpg' },
  { id: '0069', name: 'Roman Oil Lamp with a Chariot', type: 'Object', style: 'classical',
    author: 'Unknown', year: 'c. 100 CE',
    description: 'A clay lamp moulded with a racing chariot on its disc.',
    score: 4, value: 35000, image: 'artifacts/0069.jpg' },
  { id: '0070', name: 'Fragment of a Marble Frieze', type: 'Sculpture', style: 'classical',
    author: 'Unknown', year: 'c. 440 BCE',
    description: 'A broken relief section showing horsemen in a slow procession.',
    score: 16, value: 160000, image: 'artifacts/0070.jpg' },
  { id: '0071', name: 'Hoard of Silver Denarii', type: 'Object', style: 'classical',
    author: 'Unknown', year: 'c. 70 CE',
    description: 'A cluster of worn Roman silver coins, struck with emperors\u2019 heads.',
    score: 8, value: 70000, image: 'artifacts/0071.jpg' },
  { id: '0072', name: 'Bronze Statuette of a Dancer', type: 'Sculpture', style: 'classical',
    author: 'Unknown', year: 'c. 300 BCE',
    description: 'A small bronze figure caught mid-step, drapery swung wide.',
    score: 14, value: 140000, image: 'artifacts/0072.jpg' },

  /* ===================== EGYPTIAN ===================== */
  { id: '0073', name: 'Bust of Nefertiti', type: 'Sculpture', style: 'egyptian',
    author: 'Thutmose', year: 'c. 1345 BCE',
    description: 'A painted limestone bust of a queen, poised and famously serene.',
    score: 212, value: 2080000, image: 'artifacts/0073.jpg' },
  { id: '0074', name: 'The Narmer Palette', type: 'Object', style: 'egyptian',
    author: 'Unknown', year: 'c. 3100 BCE',
    description: 'A carved siltstone palette marking the union of Upper and Lower Egypt.',
    score: 158, value: 1520000, image: 'artifacts/0074.jpg' },
  { id: '0075', name: 'Statue of Khafre Enthroned', type: 'Sculpture', style: 'egyptian',
    author: 'Unknown', year: 'c. 2570 BCE',
    description: 'A pharaoh sits in diorite, a falcon god sheltering the back of his head.',
    score: 124, value: 1190000, image: 'artifacts/0075.jpg' },
  { id: '0076', name: 'The Book of the Dead of Ani', type: 'Manuscript', style: 'egyptian',
    author: 'Unknown', year: 'c. 1250 BCE',
    description: 'A long illustrated papyrus guiding a scribe through the afterlife.',
    score: 132, value: 1270000, image: 'artifacts/0076.jpg' },
  { id: '0077', name: 'Sarcophagus of a High Priest', type: 'Object', style: 'egyptian',
    author: 'Unknown', year: 'c. 1000 BCE',
    description: 'A nested coffin painted with protective deities and dense text.',
    score: 76, value: 740000, image: 'artifacts/0077.jpg' },
  { id: '0078', name: 'Statue of a Seated Scribe', type: 'Sculpture', style: 'egyptian',
    author: 'Unknown', year: 'c. 2450 BCE',
    description: 'A scribe sits cross-legged, papyrus open, eyes inlaid and alert.',
    score: 64, value: 630000, image: 'artifacts/0078.jpg' },
  { id: '0079', name: 'Canopic Jar with a Jackal Head', type: 'Object', style: 'egyptian',
    author: 'Unknown', year: 'c. 1100 BCE',
    description: 'An alabaster jar topped with a jackal, made to hold an organ of the dead.',
    score: 28, value: 280000, image: 'artifacts/0079.jpg' },
  { id: '0080', name: 'Painted Tomb Relief of Offering Bearers', type: 'Sculpture', style: 'egyptian',
    author: 'Unknown', year: 'c. 1400 BCE',
    description: 'A carved and painted file of servants carrying food to a tomb.',
    score: 31, value: 310000, image: 'artifacts/0080.jpg' },
  { id: '0081', name: 'Faience Shabti of a Noble', type: 'Object', style: 'egyptian',
    author: 'Unknown', year: 'c. 1250 BCE',
    description: 'A small blue-green figure meant to labour for the dead in the next world.',
    score: 5, value: 45000, image: 'artifacts/0081.jpg' },
  { id: '0082', name: 'Scarab Amulet of Lapis Lazuli', type: 'Object', style: 'egyptian',
    author: 'Unknown', year: 'c. 1400 BCE',
    description: 'A beetle carved from deep blue stone, worn as a charm of renewal.',
    score: 12, value: 120000, image: 'artifacts/0082.jpg' },
  { id: '0083', name: 'Fragment of a Pyramid Text', type: 'Manuscript', style: 'egyptian',
    author: 'Unknown', year: 'c. 2300 BCE',
    description: 'A limestone block cut with columns of early funerary spells.',
    score: 19, value: 190000, image: 'artifacts/0083.jpg' },
  { id: '0084', name: 'Wooden Funerary Boat Model', type: 'Object', style: 'egyptian',
    author: 'Unknown', year: 'c. 1980 BCE',
    description: 'A painted model boat with tiny rowers, placed in a tomb for the voyage.',
    score: 17, value: 170000, image: 'artifacts/0084.jpg' },
  { id: '0085', name: 'Limestone Head of a Princess', type: 'Sculpture', style: 'egyptian',
    author: 'Unknown', year: 'c. 1350 BCE',
    description: 'A delicately carved young head, the crown of it elongated and smooth.',
    score: 44, value: 440000, image: 'artifacts/0085.jpg' },
  { id: '0086', name: 'Bronze Statuette of a Cat', type: 'Object', style: 'egyptian',
    author: 'Unknown', year: 'c. 600 BCE',
    description: 'A seated bronze cat, ears pricked, sacred to the goddess Bastet.',
    score: 23, value: 230000, image: 'artifacts/0086.jpg' },
  { id: '0087', name: 'Painted Cartonnage Mummy Mask', type: 'Object', style: 'egyptian',
    author: 'Unknown', year: 'c. 900 BCE',
    description: 'A gilded mask of layered linen, the face calm and wide-eyed.',
    score: 39, value: 390000, image: 'artifacts/0087.jpg' },
  { id: '0088', name: 'Ostracon with a Sketch of a Cat', type: 'Manuscript', style: 'egyptian',
    author: 'Unknown', year: 'c. 1200 BCE',
    description: 'A limestone flake bearing a quick, witty ink drawing of an animal.',
    score: 7, value: 60000, image: 'artifacts/0088.jpg' },
  { id: '0089', name: 'Granite Sphinx of a King', type: 'Sculpture', style: 'egyptian',
    author: 'Unknown', year: 'c. 1850 BCE',
    description: 'A small recumbent sphinx, the king\u2019s face set on a lion\u2019s body.',
    score: 58, value: 570000, image: 'artifacts/0089.jpg' },

  /* ===================== MEDIEVAL ===================== */
  { id: '0090', name: 'The Bayeux Tapestry', type: 'Object', style: 'medieval',
    author: 'Unknown', year: 'c. 1077',
    description: 'An embroidered linen frieze recounting a conquest in seventy scenes.',
    score: 168, value: 1620000, image: 'artifacts/0090.jpg' },
  { id: '0091', name: 'The Book of Kells', type: 'Manuscript', style: 'medieval',
    author: 'Unknown', year: 'c. 800',
    description: 'A gospel book of dazzling interlace, every initial alive with detail.',
    score: 178, value: 1720000, image: 'artifacts/0091.jpg' },
  { id: '0092', name: 'The Lindisfarne Gospels', type: 'Manuscript', style: 'medieval',
    author: 'Eadfrith of Lindisfarne', year: 'c. 715',
    description: 'A gospel manuscript fusing Celtic, Saxon and Mediterranean ornament.',
    score: 146, value: 1400000, image: 'artifacts/0092.jpg' },
  { id: '0093', name: 'Reliquary Bust of a Saint', type: 'Sculpture', style: 'medieval',
    author: 'Unknown', year: 'c. 1175',
    description: 'A gilded silver head made to hold and honour a holy relic.',
    score: 67, value: 660000, image: 'artifacts/0093.jpg' },
  { id: '0094', name: 'Stained Glass Panel of a Prophet', type: 'Object', style: 'medieval',
    author: 'Unknown', year: 'c. 1150',
    description: 'A glowing window panel, lead-lined, a robed prophet at its centre.',
    score: 41, value: 410000, image: 'artifacts/0094.jpg' },
  { id: '0095', name: 'Carved Tympanum of the Last Judgement', type: 'Sculpture', style: 'medieval',
    author: 'Unknown', year: 'c. 1130',
    description: 'A stone doorway relief crowded with the saved and the damned.',
    score: 54, value: 530000, image: 'artifacts/0095.jpg' },
  { id: '0096', name: 'Illuminated Book of Hours', type: 'Manuscript', style: 'medieval',
    author: 'Unknown', year: 'c. 1410',
    description: 'A private prayer book, each page bordered with gold and twining leaf.',
    score: 48, value: 480000, image: 'artifacts/0096.jpg' },
  { id: '0097', name: 'Limoges Enamel Casket', type: 'Object', style: 'medieval',
    author: 'Unknown', year: 'c. 1200',
    description: 'A small copper casket enamelled in deep blue with gilded saints.',
    score: 37, value: 370000, image: 'artifacts/0097.jpg' },
  { id: '0098', name: 'Carved Ivory Diptych', type: 'Object', style: 'medieval',
    author: 'Unknown', year: 'c. 1350',
    description: 'A hinged ivory pair, scenes of the Passion cut in tiny relief.',
    score: 33, value: 330000, image: 'artifacts/0098.jpg' },
  { id: '0099', name: 'Crusader-Era Sword', type: 'Object', style: 'medieval',
    author: 'Unknown', year: 'c. 1250',
    description: 'A straight cross-hilted blade, the steel pitted but the form severe.',
    score: 15, value: 150000, image: 'artifacts/0099.jpg' },
  { id: '0100', name: 'Painted Wooden Crucifix', type: 'Sculpture', style: 'medieval',
    author: 'Unknown', year: 'c. 1250',
    description: 'A carved Christ figure on a cross, paint worn to bare wood in places.',
    score: 26, value: 260000, image: 'artifacts/0100.jpg' },
  { id: '0101', name: 'Monastic Antiphonary Leaf', type: 'Manuscript', style: 'medieval',
    author: 'Unknown', year: 'c. 1300',
    description: 'A large chant-book leaf with square notation and a red initial.',
    score: 9, value: 80000, image: 'artifacts/0101.jpg' },
  { id: '0102', name: 'Bronze Aquamanile in the Form of a Lion', type: 'Object', style: 'medieval',
    author: 'Unknown', year: 'c. 1240',
    description: 'A water vessel cast as a lion, used for washing hands at table.',
    score: 21, value: 210000, image: 'artifacts/0102.jpg' },
  { id: '0103', name: 'Pilgrim Badge of a Shrine', type: 'Object', style: 'medieval',
    author: 'Unknown', year: 'c. 1400',
    description: 'A small lead-alloy badge bought and worn by a returning pilgrim.',
    score: 3, value: 30000, image: 'artifacts/0103.jpg' },
  { id: '0104', name: 'Carved Capital with Foliage', type: 'Sculpture', style: 'medieval',
    author: 'Unknown', year: 'c. 1120',
    description: 'A column capital cut with deep, curling stylised leaves.',
    score: 11, value: 110000, image: 'artifacts/0104.jpg' },
  { id: '0105', name: 'Gothic Altarpiece Wing', type: 'Painting', style: 'medieval',
    author: 'Unknown', year: 'c. 1430',
    description: 'A hinged panel of saints under crocketed gilded canopies.',
    score: 29, value: 290000, image: 'artifacts/0105.jpg' },
  { id: '0106', name: 'Chess Piece of Walrus Ivory', type: 'Object', style: 'medieval',
    author: 'Unknown', year: 'c. 1175',
    description: 'A carved gaming piece, a seated king with a sword across his knees.',
    score: 18, value: 180000, image: 'artifacts/0106.jpg' },

  /* ===================== ASIAN ===================== */
  { id: '0107', name: 'Along the River During the Qingming Festival', type: 'Painting', style: 'asian',
    author: 'Zhang Zeduan', year: 'c. 1120',
    description: 'A vast handscroll teeming with a city\u2019s life along a winding river.',
    score: 174, value: 1680000, image: 'artifacts/0107.jpg' },
  { id: '0108', name: 'Standing Bodhisattva, Gilt Bronze', type: 'Sculpture', style: 'asian',
    author: 'Unknown', year: 'c. 700',
    description: 'A serene gilt-bronze figure, robes falling in even rhythmic folds.',
    score: 88, value: 860000, image: 'artifacts/0108.jpg' },
  { id: '0109', name: 'Blue-and-White Dragon Jar', type: 'Object', style: 'asian',
    author: 'Imperial Kilns, Jingdezhen', year: 'c. 1430',
    description: 'A porcelain jar painted in cobalt with a dragon among scrolling cloud.',
    score: 79, value: 770000, image: 'artifacts/0109.jpg' },
  { id: '0110', name: 'Samurai Armour of Lacquered Plates', type: 'Object', style: 'asian',
    author: 'Unknown', year: 'c. 1560',
    description: 'A full armour of laced lacquer plates, the helmet crested with horns.',
    score: 71, value: 700000, image: 'artifacts/0110.jpg' },
  { id: '0111', name: 'Ink Landscape of Mountains and Mist', type: 'Painting', style: 'asian',
    author: 'Unknown', year: 'c. 1300',
    description: 'A hanging scroll of far peaks dissolving into pale washed mist.',
    score: 46, value: 460000, image: 'artifacts/0111.jpg' },
  { id: '0112', name: 'Celadon Vase with Incised Lotus', type: 'Object', style: 'asian',
    author: 'Unknown', year: 'c. 1150',
    description: 'A pale green-glazed vase, lotus scrolls cut faintly beneath the glaze.',
    score: 42, value: 420000, image: 'artifacts/0112.jpg' },
  { id: '0113', name: 'Folding Screen of Cranes and Pines', type: 'Painting', style: 'asian',
    author: 'Unknown', year: 'c. 1620',
    description: 'A six-panel gold-ground screen with cranes among ancient pines.',
    score: 56, value: 550000, image: 'artifacts/0113.jpg' },
  { id: '0114', name: 'Bronze Ritual Wine Vessel', type: 'Object', style: 'asian',
    author: 'Unknown', year: 'c. 1100 BCE',
    description: 'A cast bronze vessel covered in dense, abstract animal-mask design.',
    score: 63, value: 620000, image: 'artifacts/0114.jpg' },
  { id: '0115', name: 'Illustrated Tale Handscroll', type: 'Manuscript', style: 'asian',
    author: 'Unknown', year: 'c. 1250',
    description: 'A narrative handscroll of court scenes painted in bright mineral colour.',
    score: 51, value: 500000, image: 'artifacts/0115.jpg' },
  { id: '0116', name: 'Wood Sculpture of a Guardian King', type: 'Sculpture', style: 'asian',
    author: 'Unknown', year: 'c. 1200',
    description: 'A fierce temple guardian carved from wood, mid-stride and shouting.',
    score: 49, value: 490000, image: 'artifacts/0116.jpg' },
  { id: '0117', name: 'Jade Burial Disc', type: 'Object', style: 'asian',
    author: 'Unknown', year: 'c. 200 BCE',
    description: 'A flat ringed disc of worked jade, placed with the honoured dead.',
    score: 34, value: 340000, image: 'artifacts/0117.jpg' },
  { id: '0118', name: 'Woodblock Print of an Actor', type: 'Painting', style: 'asian',
    author: 'Unknown', year: 'c. 1795',
    description: 'A bold print of a kabuki actor frozen in a dramatic pose.',
    score: 24, value: 240000, image: 'artifacts/0118.jpg' },
  { id: '0119', name: 'Lacquer Writing Box with Gold Maki-e', type: 'Object', style: 'asian',
    author: 'Unknown', year: 'c. 1650',
    description: 'A black lacquer box, its lid sprinkled with a fine gold landscape.',
    score: 27, value: 270000, image: 'artifacts/0119.jpg' },
  { id: '0120', name: 'Sandstone Head of the Buddha', type: 'Sculpture', style: 'asian',
    author: 'Unknown', year: 'c. 550',
    description: 'A carved head with lowered eyes, the stone weathered soft.',
    score: 38, value: 380000, image: 'artifacts/0120.jpg' },
  { id: '0121', name: 'Tea Bowl with a Black Glaze', type: 'Object', style: 'asian',
    author: 'Unknown', year: 'c. 1580',
    description: 'A hand-formed tea bowl prized for its irregular, quiet surface.',
    score: 13, value: 130000, image: 'artifacts/0121.jpg' },
  { id: '0122', name: 'Bronze Mirror with a Cosmic Design', type: 'Object', style: 'asian',
    author: 'Unknown', year: 'c. 200',
    description: 'A cast mirror, its back patterned with stars and abstract creatures.',
    score: 16, value: 160000, image: 'artifacts/0122.jpg' },
  { id: '0123', name: 'Calligraphy Album Leaf', type: 'Manuscript', style: 'asian',
    author: 'Unknown', year: 'c. 1400',
    description: 'A single album leaf of running-script poetry, ink swift and sure.',
    score: 19, value: 190000, image: 'artifacts/0123.jpg' },
  { id: '0124', name: 'Glazed Tomb Figure of a Horse', type: 'Sculpture', style: 'asian',
    author: 'Unknown', year: 'c. 720',
    description: 'A three-colour glazed earthenware horse, head turned and alert.',
    score: 31, value: 310000, image: 'artifacts/0124.jpg' },
  { id: '0125', name: 'Painted Hand Fan with Birds', type: 'Object', style: 'asian',
    author: 'Unknown', year: 'c. 1700',
    description: 'A folding fan painted with sparrows on a flowering branch.',
    score: 5, value: 45000, image: 'artifacts/0125.jpg' },
  { id: '0126', name: 'Carved Jade Belt Plaque', type: 'Object', style: 'asian',
    author: 'Unknown', year: 'c. 800',
    description: 'A rectangular jade plaque worked with a coiling dragon.',
    score: 8, value: 70000, image: 'artifacts/0126.jpg' },
  { id: '0127', name: 'Stoneware Jar with an Ash Glaze', type: 'Object', style: 'asian',
    author: 'Unknown', year: 'c. 1300',
    description: 'A plain, robust storage jar, its glaze pooled thick at the foot.',
    score: 4, value: 35000, image: 'artifacts/0127.jpg' },

  /* ===================== ISLAMIC ===================== */
  { id: '0128', name: 'Blue Qur\u2019an Folio', type: 'Manuscript', style: 'islamic',
    author: 'Unknown', year: 'c. 900',
    description: 'A folio of gold Kufic script on parchment dyed deep indigo.',
    score: 152, value: 1460000, image: 'artifacts/0128.jpg' },
  { id: '0129', name: 'The Baptistère de Saint Louis', type: 'Object', style: 'islamic',
    author: 'Muhammad ibn al-Zayn', year: 'c. 1320',
    description: 'A brass basin inlaid with silver, crowded with hunters and courtiers.',
    score: 97, value: 950000, image: 'artifacts/0129.jpg' },
  { id: '0130', name: 'Lustreware Bowl with a Courtly Scene', type: 'Object', style: 'islamic',
    author: 'Unknown', year: 'c. 1200',
    description: 'A bowl glazed with a metallic lustre, a seated figure at its centre.',
    score: 36, value: 360000, image: 'artifacts/0130.jpg' },
  { id: '0131', name: 'Carved Wooden Minbar Panel', type: 'Sculpture', style: 'islamic',
    author: 'Unknown', year: 'c. 1150',
    description: 'A pulpit panel of interlocking carved stars and tendrils.',
    score: 44, value: 440000, image: 'artifacts/0131.jpg' },
  { id: '0132', name: 'Illuminated Qur\u2019an Frontispiece', type: 'Manuscript', style: 'islamic',
    author: 'Unknown', year: 'c. 1370',
    description: 'A double page of dense geometric gold-and-lapis ornament.',
    score: 58, value: 570000, image: 'artifacts/0132.jpg' },
  { id: '0133', name: 'Mosque Lamp of Enamelled Glass', type: 'Object', style: 'islamic',
    author: 'Unknown', year: 'c. 1340',
    description: 'A glass lamp painted in enamel with bands of bold inscription.',
    score: 41, value: 410000, image: 'artifacts/0133.jpg' },
  { id: '0134', name: 'Silk Carpet with a Garden Design', type: 'Object', style: 'islamic',
    author: 'Unknown', year: 'c. 1600',
    description: 'A carpet woven as a walled garden, channels of water crossing it.',
    score: 62, value: 610000, image: 'artifacts/0134.jpg' },
  { id: '0135', name: 'Inlaid Brass Pen Box', type: 'Object', style: 'islamic',
    author: 'Unknown', year: 'c. 1280',
    description: 'A scribe\u2019s box of brass, inlaid with silver figures and inscription.',
    score: 28, value: 280000, image: 'artifacts/0135.jpg' },
  { id: '0136', name: 'Page from a Dispersed Shahnama', type: 'Manuscript', style: 'islamic',
    author: 'Unknown', year: 'c. 1440',
    description: 'A manuscript page of an epic battle, figures small and brilliantly dressed.',
    score: 47, value: 470000, image: 'artifacts/0136.jpg' },
  { id: '0137', name: 'Carved Stucco Wall Panel', type: 'Sculpture', style: 'islamic',
    author: 'Unknown', year: 'c. 1000',
    description: 'A panel of moulded stucco, vine scrolls cut in crisp low relief.',
    score: 14, value: 140000, image: 'artifacts/0137.jpg' },
  { id: '0138', name: 'Glazed Tile with a Star Pattern', type: 'Object', style: 'islamic',
    author: 'Unknown', year: 'c. 1260',
    description: 'A star-shaped tile painted with cobalt and turquoise foliage.',
    score: 7, value: 60000, image: 'artifacts/0138.jpg' },
  { id: '0139', name: 'Bronze Incense Burner in Animal Form', type: 'Object', style: 'islamic',
    author: 'Unknown', year: 'c. 1180',
    description: 'A pierced bronze burner cast in the shape of a stylised lion.',
    score: 22, value: 220000, image: 'artifacts/0139.jpg' },
  { id: '0140', name: 'Ivory Casket with Courtly Scenes', type: 'Object', style: 'islamic',
    author: 'Unknown', year: 'c. 1050',
    description: 'A small carved ivory box showing musicians and seated rulers.',
    score: 33, value: 330000, image: 'artifacts/0140.jpg' },

  /* ===================== PRE-COLUMBIAN ===================== */
  { id: '0141', name: 'The Aztec Sun Stone', type: 'Object', style: 'precolumbian',
    author: 'Unknown', year: 'c. 1479',
    description: 'A great carved basalt disc of cosmic cycles and a central solar face.',
    score: 164, value: 1580000, image: 'artifacts/0141.jpg' },
  { id: '0142', name: 'Olmec Colossal Head', type: 'Sculpture', style: 'precolumbian',
    author: 'Unknown', year: 'c. 900 BCE',
    description: 'A monumental basalt head, helmeted, with broad solemn features.',
    score: 118, value: 1130000, image: 'artifacts/0142.jpg' },
  { id: '0143', name: 'Moche Portrait Vessel', type: 'Object', style: 'precolumbian',
    author: 'Unknown', year: 'c. 400',
    description: 'A ceramic stirrup-spout jar modelled as a strikingly real human face.',
    score: 43, value: 430000, image: 'artifacts/0143.jpg' },
  { id: '0144', name: 'Maya Carved Lintel', type: 'Sculpture', style: 'precolumbian',
    author: 'Unknown', year: 'c. 725',
    description: 'A limestone lintel cut with a ruler and dense columns of glyphs.',
    score: 66, value: 650000, image: 'artifacts/0144.jpg' },
  { id: '0145', name: 'Gold Pectoral of a Deity', type: 'Object', style: 'precolumbian',
    author: 'Unknown', year: 'c. 1100',
    description: 'A hammered gold chest ornament in the form of a winged figure.',
    score: 72, value: 710000, image: 'artifacts/0145.jpg' },
  { id: '0146', name: 'Nazca Polychrome Bowl', type: 'Object', style: 'precolumbian',
    author: 'Unknown', year: 'c. 300',
    description: 'A ceramic bowl painted with stylised birds in many bright slips.',
    score: 26, value: 260000, image: 'artifacts/0146.jpg' },
  { id: '0147', name: 'Inca Silver Llama Figurine', type: 'Object', style: 'precolumbian',
    author: 'Unknown', year: 'c. 1500',
    description: 'A small cast silver llama, an offering left at a high mountain shrine.',
    score: 32, value: 320000, image: 'artifacts/0147.jpg' },
  { id: '0148', name: 'Maya Codex-Style Vase', type: 'Object', style: 'precolumbian',
    author: 'Unknown', year: 'c. 700',
    description: 'A cylinder vessel painted with a procession of underworld figures.',
    score: 51, value: 500000, image: 'artifacts/0148.jpg' },
  { id: '0149', name: 'Carved Jade Plaque of a Lord', type: 'Object', style: 'precolumbian',
    author: 'Unknown', year: 'c. 600',
    description: 'A thin jade plaque incised with a seated, elaborately dressed lord.',
    score: 39, value: 390000, image: 'artifacts/0149.jpg' },
  { id: '0150', name: 'Stone Mask of a Mosaic Deity', type: 'Object', style: 'precolumbian',
    author: 'Unknown', year: 'c. 1450',
    description: 'A wooden mask faced with turquoise mosaic and shell-inlaid eyes.',
    score: 84, value: 820000, image: 'artifacts/0150.jpg' },
  { id: '0151', name: 'Chavín Carved Stone Head', type: 'Sculpture', style: 'precolumbian',
    author: 'Unknown', year: 'c. 500 BCE',
    description: 'A tenon head once set into a temple wall, features fierce and abstract.',
    score: 23, value: 230000, image: 'artifacts/0151.jpg' },
  { id: '0152', name: 'Feathered Textile Fragment', type: 'Object', style: 'precolumbian',
    author: 'Unknown', year: 'c. 650',
    description: 'A scrap of cloth still bright with knotted tropical-bird feathers.',
    score: 17, value: 170000, image: 'artifacts/0152.jpg' },
  { id: '0153', name: 'Ceramic Whistle in Bird Form', type: 'Object', style: 'precolumbian',
    author: 'Unknown', year: 'c. 800',
    description: 'A small modelled bird that sounds a clear note when blown.',
    score: 6, value: 50000, image: 'artifacts/0153.jpg' },
  { id: '0154', name: 'Spindle Whorl with Incised Design', type: 'Object', style: 'precolumbian',
    author: 'Unknown', year: 'c. 900',
    description: 'A small clay weight for spinning thread, scratched with simple motifs.',
    score: 3, value: 28000, image: 'artifacts/0154.jpg' },
  { id: '0155', name: 'Veracruz Stone Yoke', type: 'Sculpture', style: 'precolumbian',
    author: 'Unknown', year: 'c. 600',
    description: 'A U-shaped carved stone linked to the ritual ballgame.',
    score: 28, value: 280000, image: 'artifacts/0155.jpg' },

  /* ===================== ROMANTICISM ===================== */
  { id: '0156', name: 'The Wanderer Above the Sea of Fog', type: 'Painting', style: 'romanticism',
    author: 'Caspar David Friedrich', year: 'c. 1818',
    description: 'A lone figure on a crag gazes over a sea of cloud-filled valleys.',
    score: 134, value: 1290000, image: 'artifacts/0156.jpg' },
  { id: '0157', name: 'The Raft of the Medusa', type: 'Painting', style: 'romanticism',
    author: 'Théodore Géricault', year: '1819',
    description: 'Survivors of a wreck strain toward a distant ship on a heaving raft.',
    score: 142, value: 1370000, image: 'artifacts/0157.jpg' },
  { id: '0158', name: 'Liberty Leading the People', type: 'Painting', style: 'romanticism',
    author: 'Eugène Delacroix', year: '1830',
    description: 'An allegorical figure carries a flag forward over the barricades.',
    score: 138, value: 1330000, image: 'artifacts/0158.jpg' },
  { id: '0159', name: 'The Hay Wain', type: 'Painting', style: 'romanticism',
    author: 'John Constable', year: '1821',
    description: 'A farm cart fords a stream beneath a sky of moving English cloud.',
    score: 96, value: 940000, image: 'artifacts/0159.jpg' },
  { id: '0160', name: 'Rain, Steam and Speed', type: 'Painting', style: 'romanticism',
    author: 'J. M. W. Turner', year: '1844',
    description: 'A train rushes across a bridge, almost dissolved in light and weather.',
    score: 108, value: 1040000, image: 'artifacts/0160.jpg' },
  { id: '0161', name: 'The Nightmare', type: 'Painting', style: 'romanticism',
    author: 'Henry Fuseli', year: '1781',
    description: 'A sleeping woman is pressed by a crouching demon as a pale horse looms.',
    score: 74, value: 720000, image: 'artifacts/0161.jpg' },
  { id: '0162', name: 'Mountain Landscape with a Storm', type: 'Painting', style: 'romanticism',
    author: 'Unknown', year: 'c. 1830',
    description: 'A small figure crosses a pass as cloud breaks over jagged peaks.',
    score: 22, value: 220000, image: 'artifacts/0162.jpg' },
  { id: '0163', name: 'A Shipwreck off a Rocky Coast', type: 'Painting', style: 'romanticism',
    author: 'Unknown', year: 'c. 1825',
    description: 'A vessel breaks apart in surf beneath a vast indifferent sky.',
    score: 18, value: 180000, image: 'artifacts/0163.jpg' },
  { id: '0164', name: 'Ruined Abbey by Moonlight', type: 'Painting', style: 'romanticism',
    author: 'Unknown', year: 'c. 1820',
    description: 'A roofless abbey stands silver under a clouded moon.',
    score: 14, value: 140000, image: 'artifacts/0164.jpg' },
  { id: '0165', name: 'A Poet\u2019s Travelling Notebook', type: 'Manuscript', style: 'romanticism',
    author: 'Unknown', year: 'c. 1820',
    description: 'A worn notebook of verse drafts, sketches and pressed flowers.',
    score: 9, value: 80000, image: 'artifacts/0165.jpg' },
  { id: '0166', name: 'Portrait of a Brooding Young Man', type: 'Painting', style: 'romanticism',
    author: 'Unknown', year: 'c. 1815',
    description: 'A youth set against a darkening sky, collar high, gaze far off.',
    score: 11, value: 110000, image: 'artifacts/0166.jpg' },
  { id: '0167', name: 'Study of Storm Clouds', type: 'Painting', style: 'romanticism',
    author: 'Workshop of John Constable', year: 'c. 1822',
    description: 'An oil sketch of nothing but moving cloud over a thin horizon.',
    score: 16, value: 160000, image: 'artifacts/0167.jpg' },
  { id: '0168', name: 'Bronze Statuette of a Lion Attacking a Horse', type: 'Sculpture', style: 'romanticism',
    author: 'Unknown', year: 'c. 1835',
    description: 'A small violent bronze group, all muscle and motion.',
    score: 24, value: 240000, image: 'artifacts/0168.jpg' },

  /* ===================== IMPRESSIONISM ===================== */
  { id: '0169', name: 'Water Lilies', type: 'Painting', style: 'impressionism',
    author: 'Claude Monet', year: 'c. 1906',
    description: 'A pond surface dissolved into floating colour and reflected sky.',
    score: 158, value: 1520000, image: 'artifacts/0169.jpg' },
  { id: '0170', name: 'Impression, Sunrise', type: 'Painting', style: 'impressionism',
    author: 'Claude Monet', year: '1872',
    description: 'A harbour at dawn, the sun a smudged orange disc over grey water.',
    score: 168, value: 1620000, image: 'artifacts/0170.jpg' },
  { id: '0171', name: 'Bal du moulin de la Galette', type: 'Painting', style: 'impressionism',
    author: 'Pierre-Auguste Renoir', year: '1876',
    description: 'A crowd dances and talks under trees in dappled afternoon light.',
    score: 144, value: 1390000, image: 'artifacts/0171.jpg' },
  { id: '0172', name: 'The Ballet Class', type: 'Painting', style: 'impressionism',
    author: 'Edgar Degas', year: 'c. 1874',
    description: 'Dancers wait and stretch under the eye of an old ballet master.',
    score: 126, value: 1210000, image: 'artifacts/0172.jpg' },
  { id: '0173', name: 'Luncheon of the Boating Party', type: 'Painting', style: 'impressionism',
    author: 'Pierre-Auguste Renoir', year: '1881',
    description: 'Friends linger over wine on a riverside balcony in summer light.',
    score: 132, value: 1270000, image: 'artifacts/0173.jpg' },
  { id: '0174', name: 'Boulevard at Dusk', type: 'Painting', style: 'impressionism',
    author: 'Unknown', year: 'c. 1885',
    description: 'A city street seen from above, figures reduced to quick warm flecks.',
    score: 28, value: 280000, image: 'artifacts/0174.jpg' },
  { id: '0175', name: 'Riverbank in Spring', type: 'Painting', style: 'impressionism',
    author: 'Unknown', year: 'c. 1880',
    description: 'A quick study of light on water, brushwork loose and bright.',
    score: 17, value: 170000, image: 'artifacts/0175.jpg' },
  { id: '0176', name: 'Woman with a Parasol in a Garden', type: 'Painting', style: 'impressionism',
    author: 'Unknown', year: 'c. 1883',
    description: 'A figure shaded against summer flowers, edges blurred by sun.',
    score: 21, value: 210000, image: 'artifacts/0176.jpg' },
  { id: '0177', name: 'Haystacks in Late Afternoon', type: 'Painting', style: 'impressionism',
    author: 'Unknown', year: 'c. 1890',
    description: 'Two haystacks catching low gold light against a cooling field.',
    score: 33, value: 330000, image: 'artifacts/0177.jpg' },
  { id: '0178', name: 'Still Life with Apples and a Jug', type: 'Painting', style: 'impressionism',
    author: 'Unknown', year: 'c. 1888',
    description: 'A plain table study, fruit and earthenware built from broken colour.',
    score: 12, value: 120000, image: 'artifacts/0178.jpg' },
  { id: '0179', name: 'Café Terrace in the Evening', type: 'Painting', style: 'impressionism',
    author: 'Unknown', year: 'c. 1887',
    description: 'Lamplight spills from a café onto a street of soft blue shadow.',
    score: 26, value: 260000, image: 'artifacts/0179.jpg' },
  { id: '0180', name: 'Small Bronze of a Dancer', type: 'Sculpture', style: 'impressionism',
    author: 'Workshop of Edgar Degas', year: 'c. 1885',
    description: 'A bronze dancer rests one foot forward, surface left rough and alive.',
    score: 44, value: 440000, image: 'artifacts/0180.jpg' },

  /* ===================== MODERNISM ===================== */
  { id: '0181', name: 'The Persistence of Memory', type: 'Painting', style: 'modernism',
    author: 'Salvador Dalí', year: '1931',
    description: 'Soft melting watches drape over a still, dreamlike shoreline.',
    score: 186, value: 1800000, image: 'artifacts/0181.jpg' },
  { id: '0182', name: 'Les Demoiselles d\u2019Avignon', type: 'Painting', style: 'modernism',
    author: 'Pablo Picasso', year: '1907',
    description: 'Five angular figures stare out, faces sharp as carved masks.',
    score: 176, value: 1700000, image: 'artifacts/0182.jpg' },
  { id: '0183', name: 'The Scream', type: 'Painting', style: 'modernism',
    author: 'Edvard Munch', year: '1893',
    description: 'A figure clutches its face on a bridge under a blood-orange sky.',
    score: 192, value: 1880000, image: 'artifacts/0183.jpg' },
  { id: '0184', name: 'Composition with Red, Blue and Yellow', type: 'Painting', style: 'modernism',
    author: 'Piet Mondrian', year: '1930',
    description: 'Black lines divide white into blocks of three pure colours.',
    score: 122, value: 1170000, image: 'artifacts/0184.jpg' },
  { id: '0185', name: 'The Kiss', type: 'Painting', style: 'modernism',
    author: 'Gustav Klimt', year: 'c. 1908',
    description: 'A couple embrace, wrapped together in a single field of gold pattern.',
    score: 164, value: 1580000, image: 'artifacts/0185.jpg' },
  { id: '0186', name: 'Bird in Space', type: 'Sculpture', style: 'modernism',
    author: 'Constantin Brâncuși', year: 'c. 1924',
    description: 'A polished bronze form pared down to the pure idea of flight.',
    score: 118, value: 1130000, image: 'artifacts/0186.jpg' },
  { id: '0187', name: 'Black Square', type: 'Painting', style: 'modernism',
    author: 'Kazimir Malevich', year: '1915',
    description: 'A single black square on white — painting reduced to its limit.',
    score: 104, value: 1000000, image: 'artifacts/0187.jpg' },
  { id: '0188', name: 'Reclining Figure in Bronze', type: 'Sculpture', style: 'modernism',
    author: 'Unknown', year: 'c. 1938',
    description: 'A smooth, pierced bronze body, somewhere between figure and landscape.',
    score: 58, value: 570000, image: 'artifacts/0188.jpg' },
  { id: '0189', name: 'Cubist Still Life with a Guitar', type: 'Painting', style: 'modernism',
    author: 'Unknown', year: 'c. 1913',
    description: 'A guitar and newspaper fractured into shifting overlapping planes.',
    score: 39, value: 390000, image: 'artifacts/0189.jpg' },
  { id: '0190', name: 'Abstract Composition in Grey', type: 'Painting', style: 'modernism',
    author: 'Unknown', year: 'c. 1925',
    description: 'Floating soft-edged shapes balanced across a quiet grey field.',
    score: 23, value: 230000, image: 'artifacts/0190.jpg' },
  { id: '0191', name: 'Surrealist Landscape with a Tower', type: 'Painting', style: 'modernism',
    author: 'Unknown', year: 'c. 1936',
    description: 'A lone tower on an empty plain throws an impossibly long shadow.',
    score: 31, value: 310000, image: 'artifacts/0191.jpg' },
  { id: '0192', name: 'Expressionist Portrait in Green', type: 'Painting', style: 'modernism',
    author: 'Unknown', year: 'c. 1919',
    description: 'A face built from harsh, unnatural colour and slashing strokes.',
    score: 27, value: 270000, image: 'artifacts/0192.jpg' },
  { id: '0193', name: 'Constructivist Poster Design', type: 'Manuscript', style: 'modernism',
    author: 'Unknown', year: 'c. 1923',
    description: 'A bold poster maquette of red diagonals and stark sans-serif type.',
    score: 13, value: 130000, image: 'artifacts/0193.jpg' },
  { id: '0194', name: 'Welded Steel Abstract', type: 'Sculpture', style: 'modernism',
    author: 'Unknown', year: 'c. 1948',
    description: 'A jagged open construction of welded steel rods and plates.',
    score: 19, value: 190000, image: 'artifacts/0194.jpg' },
  { id: '0195', name: 'Geometric Study in Primary Colour', type: 'Painting', style: 'modernism',
    author: 'Unknown', year: 'c. 1929',
    description: 'A small disciplined grid of red, blue and yellow rectangles.',
    score: 8, value: 70000, image: 'artifacts/0195.jpg' },

  /* ===================== CONTEMPORARY ===================== */
  { id: '0196', name: 'Balloon Dog (Orange)', type: 'Sculpture', style: 'contemporary',
    author: 'Jeff Koons', year: 'c. 1994',
    description: 'A mirror-polished steel sculpture of a twisted toy balloon dog.',
    score: 112, value: 1080000, image: 'artifacts/0196.jpg' },
  { id: '0197', name: 'Untitled (Colour Field)', type: 'Painting', style: 'contemporary',
    author: 'Unknown', year: 'c. 1968',
    description: 'Vast soft bands of saturated colour, meant to be stood close to.',
    score: 46, value: 460000, image: 'artifacts/0197.jpg' },
  { id: '0198', name: 'Neon Text Installation', type: 'Object', style: 'contemporary',
    author: 'Unknown', year: 'c. 1998',
    description: 'A looping phrase bent in glowing neon tubing against a bare wall.',
    score: 34, value: 340000, image: 'artifacts/0198.jpg' },
  { id: '0199', name: 'Large Drip Painting', type: 'Painting', style: 'contemporary',
    author: 'Unknown', year: 'c. 1952',
    description: 'A web of poured and flung paint covering the canvas edge to edge.',
    score: 63, value: 620000, image: 'artifacts/0199.jpg' },
  { id: '0200', name: 'Photorealist Diner Scene', type: 'Painting', style: 'contemporary',
    author: 'Unknown', year: 'c. 1975',
    description: 'A chrome diner front painted with cool, glassy precision.',
    score: 29, value: 290000, image: 'artifacts/0200.jpg' },
  { id: '0201', name: 'Stainless Steel Mirror Form', type: 'Sculpture', style: 'contemporary',
    author: 'Unknown', year: 'c. 2001',
    description: 'A bean-like polished form that swallows the room in its surface.',
    score: 71, value: 700000, image: 'artifacts/0201.jpg' },
  { id: '0202', name: 'Spray-Paint Mural Study', type: 'Painting', style: 'contemporary',
    author: 'Unknown', year: 'c. 2006',
    description: 'A stencilled street-art image preserved on a cut section of wall.',
    score: 41, value: 410000, image: 'artifacts/0202.jpg' },
  { id: '0203', name: 'Minimalist Cube Arrangement', type: 'Sculpture', style: 'contemporary',
    author: 'Unknown', year: 'c. 1969',
    description: 'A row of identical plain cubes spaced at exact intervals.',
    score: 22, value: 220000, image: 'artifacts/0203.jpg' },
  { id: '0204', name: 'Large-Scale Colour Photograph', type: 'Object', style: 'contemporary',
    author: 'Unknown', year: 'c. 2003',
    description: 'A wall-sized photograph of an empty modern interior, coolly lit.',
    score: 18, value: 180000, image: 'artifacts/0204.jpg' },
  { id: '0205', name: 'Found-Object Assemblage', type: 'Object', style: 'contemporary',
    author: 'Unknown', year: 'c. 1961',
    description: 'A wall piece built from salvaged wood, wire and worn metal.',
    score: 14, value: 140000, image: 'artifacts/0205.jpg' },
  { id: '0206', name: 'Video Still on Light Box', type: 'Object', style: 'contemporary',
    author: 'Unknown', year: 'c. 2009',
    description: 'A single cinematic frame mounted as a glowing back-lit panel.',
    score: 9, value: 80000, image: 'artifacts/0206.jpg' },

  /* ===================== POP CULTURE ===================== */
  { id: '0207', name: 'A Rock Legend\u2019s Stage Guitar', type: 'Object', style: 'popculture',
    author: 'Unknown', year: '1969',
    description: 'A worn electric guitar played through an era-defining world tour.',
    score: 88, value: 860000, image: 'artifacts/0207.jpg' },
  { id: '0208', name: 'The Adventurer\u2019s Leather Whip', type: 'Object', style: 'popculture',
    author: 'Unknown', year: '1981',
    description: 'A coiled bullwhip carried by the hero of a beloved adventure film.',
    score: 47, value: 470000, image: 'artifacts/0208.jpg' },
  { id: '0209', name: 'A Pop Artist\u2019s Soup-Can Silkscreen', type: 'Painting', style: 'popculture',
    author: 'Unknown', year: 'c. 1964',
    description: 'A repeated, brightly inked image of an ordinary supermarket product.',
    score: 96, value: 940000, image: 'artifacts/0209.jpg' },
  { id: '0210', name: 'Original Annotated Film Script', type: 'Manuscript', style: 'popculture',
    author: 'Unknown', year: '1977',
    description: 'A shooting script thick with hand-written margin notes and cuts.',
    score: 29, value: 290000, image: 'artifacts/0210.jpg' },
];
